[telegram]
apikey = "xxxxxxxxx:xxxxxxxxxxxxxxxxxx"
chat_ids = [xxxxxxxxx, xxxxxxxxx]
dynaconf_merge = true

[mqtt]
password = "xxxxxxxxxx"
dynaconf_merge = true

[unifidoorbell]
password = "xxxxxxxxxxxx"
dynaconf_merge = true

[unifiprotect]
password = "xxxxxxxxxxx"
dynaconf_merge = true